### PR TITLE
feat(xcode): add Xcode 11.2.1 support, add friendly debug info

### PR DESCRIPTION
**Pull request by paradite**
- add Xcode 11.2.1 support 
  - https://github.com/macacajs/xctestwd-frameworks/pull/2
  - https://github.com/macacajs/xctestwd-frameworks-11.1
- add friendly debug info for retry

### CODE REVIEW

**Comment by xudafeng** [comment]
+1

**Comment by ganjarpanji** [comment]
how to get the latest fix? checkout and rebuild by our self in node_modules/xctestwd ?

**Comment by paradite** [comment]
> how to get the latest fix? checkout and rebuild by our self in node_modules/xctestwd ?

Just uninstall whatever that is dependent on xctestwd and reinstall again. Or manually install xctestwd if you know what you are doing.

**Comment by ganjarpanji** [comment]
hope we will have new release soon, so we can add it on the app-inspector as well. thanks anyway

**Comment by paradite** [comment]
> hope we will have new release soon, so we can add it on the app-inspector as well. thanks anyway

Uninstalling and reinstalling app-inspector should make it work with Xcode 11.2.1. There is no need to release a new version of app-inspector.

**Pull request merged**
